### ISSUE TITLE
no response from nibeGW

### ISSUE THREAD

**Issue by Coffee0297** [elupus/esphome-nibe#14]
Hello, thanks alot for this addon. im having a little issue, i can't get the homeassistant Nibe heatpump:https://rc.home-assistant.io/integrations/nibe_heatpump
To connect. it says my remote ip or read port is wrong, but im using all defaults. 
Im using HA beta to get latest fixes.

![image](https://user-images.githubusercontent.com/43273303/198898872-b2e76293-5b1e-422c-aab4-b8f540961931.png)
![image](https://user-images.githubusercontent.com/43273303/198898891-5e6fed7d-0665-47b9-8a8b-5c2dc3611b23.png)
![image](https://user-images.githubusercontent.com/43273303/198898921-da42a173-d9ac-41bd-87de-93bc7b520fd6.png)
But as you can see the ESP get the udp from HA it seems..

**Comment by elupus** [comment]
Ive had oddness (and heard others) with the default ports. Set it up on 10080, 10081, 10082 and try again.

I think there is some chromecast stuff on 9999

**Comment by elupus** [comment]
Wait. Doesnt look like your pump is connected and have modbus40 enabled.

**Comment by Coffee0297** [comment]
> 

the heatpump have modbus enabled, gan grab a pic. its a VVM310 and when i disconnect the esp the heatpump errors

**Comment by Coffee0297** [comment]
![PXL_20221030_201313180](https://user-images.githubusercontent.com/43273303/198899619-a91b34da-7572-4709-9408-d60aa2bd9b73.jpg)
![PXL_20221030_201328556](https://user-images.githubusercontent.com/43273303/198899623-e4a1d6aa-465a-4346-8235-2d857dd11491.jpg)

**Comment by Coffee0297** [comment]
and seems like even with difrent ports same issue. 

Here is the part of esphome 

```# Load nibe component
external_components:
  - source: github://elupus/esphome-nibe


# Configure uart that will be used
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600


# Configure NibeGW
nibegw:
  dir_pin:
        number: GPIO3
        inverted: false
  udp:
    # The target address(s) to send data to. May be a multicast address.
    target:
      - ip: 10.0.0.225
        port: 10080
    # List of source address to accept data from, may be empty for no filter
    source:
      - 192.168.16.130

    # Optional port this device will listen to to receive read requests. Defaults to 9999
    read_port: 10081

    # Optional port this device will listen to to receive write request. Defaults to 10000
    write_port: 10082


  acknowledge:
    - MODBUS40
    - RMU40_S4

  # Constant replies to certain requests cabe made
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address?
      ]


# Accessory version response
    - address: RMU40_S4
      token: ACCESSORY
      data: [
            0xEE, # RMU ?
            0x03, # RMU version low
            0x01, # RMU version high
      ]

    # Unknown response that nibepi uses
    - address: RMU40_S4
      token: RMU_DATA
      command: RMU_WRITE
      data: [
            0x63,
            0x00,
      ]

    # Constant fixed temperature to avoid pump going into alarm.
    - address: RMU40_S4
      token: RMU_WRITE
      data: [
            0x06, # Temperature
            0x14, # degrees low
            0x00, # degrees hight
      ]

# Some helper functions to restart ESPHome from HA
button:
- platform: restart
  name: Nibegw Restart
- platform: safe_mode
  name: Nibegw Safe Mode Boot```

**Comment by elupus** [comment]
Are you running in docker or some other virtualization system? If so you need to set up port forward.

**Comment by Coffee0297** [comment]
> Are you running in docker or some other virtualization system? If so you need to set up port forward.

im running HA in a proxmox. but all other esp have 0 issues, but that may be bc default ports?

**Comment by Coffee0297** [comment]
sadly port forward did not fix it either.. can i enable some deep debug to see what the esp recives on the ip? and if it sends anything

**Comment by elupus** [comment]
Well, this is not standard esphome communication. It is nibegw communication.

You need to port forward the 9999/local listening port into your HA device if its not on a bridged network.

Yes, you can turn on debug with these entries for logger component in home assistant.

```
homeassistant.components.nibe_heatpump: debug
nibe: debug
```

The esphpme device can be increased too:
```
nivegw:
  debug: true
```

**Comment by Coffee0297** [comment]
i tried to portforward no dice... ill try some more debugging. 
Also is it exspected that the install of this will dissable a outside heatpump? mine have not been running when the esphome was connected, but taking it off and the heatpump stated preheating. it seems to be the same rs485 but difrent ports so not sure if theres any correlation

**Comment by elupus** [comment]
It should absolutely not affect any other pumps. That even more indicate something broken with the esp connection to the pump. For example th rs485 chip always in transmit mode.

What hw are you using?

**Comment by Coffee0297** [comment]
Esp32 and a uart to rs485 
![PXL_20221101_054211504](https://user-images.githubusercontent.com/43273303/199167240-9ee1f1ad-6623-4d40-b203-eca2217724d8.jpg)
![PXL_20221101_054234190](https://user-images.githubusercontent.com/43273303/199167254-56676677-d688-4214-8bc8-d309e04cfac4.jpg)
The odd thing is the heat pump says no error

**Comment by elupus** [comment]
What type of rs485 chip is that?

**Comment by elupus** [comment]
Ps. I would have expected a debug line in the esp log, every time it sends data over udp. So once wifi is up, you should be getting logs every second.

**Comment by Coffee0297** [comment]
Max485 
Same type as I have:
https://www.amazon.com/ANMBEST-Transceiver-Arduino-Raspberry-Industrial-Control/dp/B088Q8TD4V

I apriciate all the help! 

Regarding the debug, i tried adding it but i only get a recive 6 packets in the log, nothing else. but would make sense if the Modbus is fucked..

**Comment by elupus** [comment]
Also, you could look at the rs485 lines with you oscilloscope, there should be traffic there once connected.

**Comment by elupus** [comment]
That chip needs you to control the enable pins correctly. It has not auto mode. So verify that it is connected properly and or inverted properly.

**Comment by Coffee0297** [comment]
I will check thanks, but would the heat pump not go in error if wrong flow control pin? As it shuld not get the ACK\NAK from the esp? Just trying to understand :)

**Comment by elupus** [comment]
I dont know. Maybe it hangs if bus is always busy/dominant.

**Comment by Coffee0297** [comment]
So I have it connected to the right pin, but do you change the dit pin on send or recive? This is how mine expect
High to transmit low to recive. Mine is non inverted in the config.
 
![Screenshot_20221101-092032](https://user-images.githubusercontent.com/43273303/199190334-b3a1637f-f001-46a1-8ce9-83e5c9c4359c.png)

**Comment by elupus** [comment]
Seems correct. I would look at the bus and verify that you have trafic after the esp is connected.

**Comment by elupus** [comment]
The A/B pins could potentially be swapped too. But I assumed you tested swapping those.

**Comment by Coffee0297** [comment]
Yea i had to swap a/b to clear the error from the heat pump

**Comment by elupus** [comment]
Weird. Re verify the logs. It should be printing things as it sends it out on udp.

**Comment by Coffee0297** [comment]
i poked a bit arround with the scope, have the DIR pin been tested before? to me it seems like the esp recives the first com fine, then puts the dir high as it shuld, but the dir pin do not get pulled low after the TX is done...

**Comment by elupus** [comment]
I know there are people using it. But, the way the esp pulls pins low is by high impedance pulldown i think. I think the other people have used an inverted pin.

**Comment by Coffee0297** [comment]
Yea good point .. i have tried both inverted true and false, same end result .. may just get one with auto direction and be done with it. Do we get access to more than on the Nibe uplink? Using it currently and works great, tho no actual kw produced so can't calc a cop

**Comment by elupus** [comment]
More 8nternal atate + faster rate. But not much more that is very usefull to be honest.

**Comment by elupus** [comment]
GPIO3 is part of the debug uart. That might be why it behaves wrongly.

**Comment by elupus** [comment]
I think this is resolved now. Please recheck with the new release.
