### ISSUE TITLE
Heatpump unreachable with ESP8266

### ISSUE THREAD

**Issue by Manhem** [elupus/esphome-nibe#22]
I have used the now firmware for three weeks now and everthing was working well until this night. (I was testpilot for ESP8266)
I have lost the connection to my ESP8266.
The connection to the pump is still there, so my heatpump is working.
The WiFi signal and ESPhome version is there but no values from the heatpump.
I have restart the ESP with the same result.

Logfile from ESP-home shows this:
INFO Reading configuration /config/esphome/nibe-f1145.yaml...
INFO Starting log output from 192.168.0.32 using esphome API
WARNING Can't connect to ESPHome API for 192.168.0.32: Error connecting to ('192.168.0.32', 6053): [Errno 113] Connect call failed ('192.168.0.32', 6053)
INFO Trying to reconnect to 192.168.0.32 in the background

I use Home Assistant:
Home Assistant 2022.12.1
Supervisor 2022.12.dev0901
Frontend-version: 20221208.0 - latest

**Comment by elupus** [comment]
Do you get the logs okay network or direct connection over usb?

**Comment by Manhem** [comment]
The answer I got was when I try to log wireless from ESPhome addon in Home Assistant

**Comment by elupus** [comment]
Ok. Then its not finding the esphome on the network. Either it has broken down or its not finding wifi. I think you need to connect to it with a usb cable and get logs from it that way.

**Comment by Manhem** [comment]
I have now reprogram the ESP for logging and the only thing I got was "start logging".
Then I reprogram the ESP again with baud: 0 again.
After that I got lots of text in Wireless logging:
12:01:51][C][wifi_signal.sensor:009]: WiFi Signal 'nibe-f1145_wifi_signal'
[12:01:51][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[12:01:51][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[12:01:51][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[12:01:51][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[12:01:52][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:52][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:53][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:53][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:53][D][nibegw:030]: UDP Packet with 86 bytes to send
[12:01:54][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:54][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:55][D][nibegw:030]: UDP Packet with 6 bytes to send
[12:01:55][D][nibegw:030]: UDP Packet with 6 bytes to send

But I don't get anything into Home Assistant, exept for WiFi signal and firmware version.

**Comment by elupus** [comment]
Could your home assistant computer have changed its IP address?

**Comment by Manhem** [comment]
Nope.
I have a static IP and all the other ESP's are working.
Also the IP for my Heatpump is static.

**Comment by elupus** [comment]
Any errors in home assistant? Maybe something have blocked the port you use to receive data.

**Comment by Manhem** [comment]
You mean port 9999 or 10000?
I why should it happend by it self?

**Comment by elupus** [comment]
Im just guessing here. I did note that some chromecasts kept sending to 9999, so skipped those ports myself. That said, it should not be a problem since we filter the incoming port.

Could the ESP have changed its IP? Home assistant will filter on incoming address too.

**Comment by Manhem** [comment]
The ESP has a static IP to.

**Comment by elupus** [comment]
Did you configure home assistant with the IP of the esp or with the hostname?

**Comment by Manhem** [comment]
I do everything in ESPhome addon:
esphome:
  name: ${devicename}

If this is what you mean?

**Comment by elupus** [comment]
No, when you added the nibe integration.

**Comment by Manhem** [comment]
I'm not really sure.
Where can I find that in HA?

**Comment by Manhem** [comment]
I install Nibe addon again and the first test seems okej.
No I only need to redo everything.
Very strange....

**Comment by elupus** [comment]
You should not need yo redo much i think.

**Comment by Manhem** [comment]
Everything works again.
We must see if this is going to happend later. If it does, I think there can be a problem somewhere.
For now, we leave it like it is.

**Comment by elupus** [comment]
Sounds good.
