### ISSUE TITLE
Just a small question

### ISSUE THREAD

**Issue by Manhem** [elupus/esphome-nibe#27]
If I wan't to control this in automation, how can I do what?
I can control it, if I put it in a card with the switch or slider.
I would like to set the temperature in my house, depending on when I'm home or not.
F1145 Heat Offset S1 - 47011

And if I get an alarm, how do I reset it in automation?
F1145 Alarm Reset - 45171

**Comment by elupus** [comment]
To reset alarm. Trigger the alarm reset button in your automation. In general I cant really help you with writing automations. Look to the documentation for home assistant and forums.
