### ISSUE TITLE
Not able to update on current HA installation

### ISSUE THREAD

**Issue by Lieberkind72** [elupus/esphome-nibe#40]
ESPHOME will not compile after last update.

it has worked until now, what can cause this problem ?

see below:

src/esphome/components/nibegw/NibeGwComponent.cpp: In member function 'void NibeGwComponent::callback_msg_received(const byte*, int)':
src/esphome/components/nibegw/NibeGwComponent.cpp:33:72: error: invalid cast from type 'std::__tuple_element_t<0, std::tuple<esphome::network::IPAddress, int> >' {aka 'esphome::network::IPAddress'} to type 'uint32_t' {aka 'long unsigned int'}
         if (!udp_read_.writeTo(data, len, (uint32_t)std::get<0>(*target), std::get<1>(*target))) {
                                                                        ^
src/esphome/components/nibegw/NibeGwComponent.cpp: In member function 'void NibeGwComponent::token_request_cache(AsyncUDPPacket&, byte, byte)':
src/esphome/components/nibegw/NibeGwComponent.cpp:59:52: error: conversion from 'uint32_t' {aka 'long unsigned int'} to 'esphome::network::IPAddress' is ambiguous
     network::IPAddress ip = (uint32_t)udp.remoteIP();
                                                    ^
In file included from src/esphome.h:20,
                 from src/esphome/components/nibegw/NibeGwComponent.h:9,
                 from src/esphome/components/nibegw/NibeGwComponent.cpp:1:
src/esphome/components/network/ip_address.h:55:3: note: candidate: 'esphome::network::IPAddress::IPAddress(esp_ip4_addr_t*)' <near match>
   IPAddress(esp_ip4_addr_t *other_ip) { memcpy((void *) &ip_addr_, (void *) other_ip, sizeof(esp_ip4_addr_t)); }
   ^~~~~~~~~
src/esphome/components/network/ip_address.h:55:3: note:   conversion of argument 1 would be ill-formed:
src/esphome/components/nibegw/NibeGwComponent.cpp:59:29: error: invalid conversion from 'uint32_t' {aka 'long unsigned int'} to 'esp_ip4_addr_t*' {aka 'esp_ip4_addr*'} [-fpermissive]
     network::IPAddress ip = (uint32_t)udp.remoteIP();
                             ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome.h:20,
                 from src/esphome/components/nibegw/NibeGwComponent.h:9,
                 from src/esphome/components/nibegw/NibeGwComponent.cpp:1:
src/esphome/components/network/ip_address.h:50:3: note: candidate: 'esphome::network::IPAddress::IPAddress(esp_ip6_addr_t*)' <near match>

**Comment by Tommatheussen** [comment]
Probably due to https://github.com/esphome/esphome/pull/5252
The pull request states it's a breaking change, but not listed on the ESPHome release
