### ISSUE TITLE
First step with Lilygo ESP32

### ISSUE THREAD

**Issue by frukttime** [elupus/esphome-nibe#45]
Hello,

I'm just starting to learn ESPhome and ESP32. 
My problem:
1. I connect the Board to computer
2. Make the connection in ESPhome (in my HA)
3. Edit the YAML (I take it from the example) and I get an error with OTA (Secret 'OTA_PASSWORD' not defined)
4. I find solutions for OTA:
```

esphome:
  on_boot:
    - lambda: |-
        id(ota_id).set_auth_password("your_new_ota_password");

ota:
  password: "Old password"
  id: ota_id`
```
After solutions with ota i have next problem with - ssid: !secret WIFI_SSID
I think after WIFI_SSID coming WIFI_PASSWORD

What is my fault?

**Comment by elupus** [comment]
I'm not sure what it is you are trying to do. Secrets are part of the home assistant plugin. Just press the secrets button and make sure you have values there. You need to have enteried the name of your wifi network and the password to it for the device to be able to connect. I can not handle that type of support questions here, you need to read up on esphome in general.
