### ISSUE TITLE
Conversion of IPAddress to non-scalar type

### ISSUE THREAD

**Issue by Pivk77** [elupus/esphome-nibe#48]
I get the following error with the provided example and changed for my use case

![image](https://github.com/elupus/esphome-nibe/assets/25513701/5f67a002-54dc-4b00-a6f5-b2f608d0bfa4)

**Comment by elupus** [comment]
Please upgrade the component

**Comment by Pivk77** [comment]
And how do i do that? i guess it pulls the code directly from github?

**Comment by elupus** [comment]
It does, but you may have to clear cache in esphome in some way.

**Comment by Pivk77** [comment]
I deleted everything and redownloaded via homeassistant and manualy and still the same issue

**Comment by Pivk77** [comment]
I'm using esphome dev and yes it is updated ... could the issue be the dev esphome addon?

**Comment by elupus** [comment]
Maybe. Yes. But if it is then i need to figure out why dev doesnt work.

**Comment by Pivk77** [comment]
[image: image.png][image: image.png][image: image.png]

Hi,
since i have your attention ... i'm still struggling to get the thing
working ... i have a VVM310 HP, and i cant find the enable MODBUS40 in
settings and i cant get it connected. I guess the modbus connection is ok.
I also tried different ports if some were blocked

V V pon., 30. okt. 2023 ob 17:55 je oseba Joakim Plate <
***@***.***> napisala:

**Comment by Pivk77** [comment]
also i get this error ... even if i have the devices on the same network,
but since i have homeassistant on 192.168.20.3 and esp on 192.168.20.195 it
should be fine

V V sre., 1. nov. 2023 ob 16:47 je oseba Matevž Pivk ***@***.***>
napisala:

**Comment by Pivk77** [comment]
[image: image.png]

V V sre., 1. nov. 2023 ob 18:41 je oseba Matevž Pivk ***@***.***>
napisala:
