### ISSUE TITLE
Disabled configuaration entities in HomeAssistant

### ISSUE THREAD

**Issue by elbartl** [elupus/esphome-nibe#61]
Hello,

I have managed to successfully setup communication between my HA and Nibe using NibeGW with esphome. 
There are two entities in HA which are visible: "Hot Water" and "Climate System S1". The rest of the entities are all unavailable. My config is based on the yaml from example folder. The goal here is to coordinate heat pump with solar production. I would appreciate help with enabling those entities in HA. Maybe that will be beneficial for others too.

Setup: SMO 40 with Firmware: 9586 and TTGO T-CAN485 ESP32

Regards 
Bart

![Nibe_ha_1](https://github.com/elupus/esphome-nibe/assets/44022602/2807e160-0ac4-4314-a62d-576f0dadcc6e)

All entities are unavailable like that:
![Nibe_ha_2](https://github.com/elupus/esphome-nibe/assets/44022602/659ef06c-dfc6-4452-b53e-0009add34663)

**Comment by elupus** [comment]
Go to configuration of that entity and enable it.

**Comment by elbartl** [comment]
Wow that works, thanks. Did not think it is that easy. Appreciate your work and quick help!
