### ISSUE TITLE
SMO20 supported? 

### ISSUE THREAD

**Issue by mkleijn** [elupus/esphome-nibe#7]
Hi @elupus, 

I have a SMO20 hooked up with a F2040-8. Do you know if either of these have a Modbus connection? In the HA component I see smo20 as a supported device, but I seem to remember back in the day when I needed to decide if the SMO40 was worth the extra €€€ that Modbus support was one of the distinctive features of the SMO40 over the SMO20. I hope I'm misremembering, as while I love your uplink api component so far, I rather hook up a esp32 directly at the smo and keep everything local.

Thnx,
Michiel

**Comment by mkleijn** [comment]
Found this https://github.com/yozik04/nibe/issues/41

**Comment by elupus** [comment]
For now i think we can consider it not supported.
